apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis-deployment
  labels:
    name: redis-app-pod
    app: demo-voting-app
spec:
  replicas: 1
  selector:
    matchLabels:
      name: redis-app-pod
      app: demo-voting-app
  template:
    metadata:
      name: redis 
      labels:
        name: redis-app-pod
        app: demo-voting-app
    spec: 
      containers:
      - name: redis
        image: redis:latest
        ports:
        - containerPort: 6379
---
apiVersion: v1 
kind: Service 
metadata:
 name: redis-service
 labels:
  name: redis-service
  app: demo-voting-app
spec: 
 ports:
 - port: 6379
   targetPort: 6379
 selector:
  name: redis-app-pod
  app: demo-voting-app